export const properties = (config: IPrivateConfig): IProperties => ({
  ...config,
  SIZE_NAME_CREEP: 10,

  ROLE_HARVESTER: "harvester",
  ROLE_UPGRADER: "upgrader",
  ROLE_BUILDER: "builder",
  ROLE_REFUELLER: "refueller",
  ROLE_WORKING_ABROAD_UPGRADER: "workingAbroadUpgrader",
  ROLE_WORKING_ABROAD_HARVESTER: "workingAbroadHarvester",
  ROLE_ATTACK: "attack",
  ROLE_RANGED: "ranged",

  LEVEL_1: 1,
  LEVEL_2: 2,
  LEVEL_3: 3,
  LEVEL_4: 4,

  ROOM_ENERGY_LIMIT_300: 300,
  ROOM_ENERGY_LIMIT_550: 550,
  ROOM_ENERGY_LIMIT_800: 800,
  ROOM_ENERGY_LIMIT_1300: 1300,

  FIT_WORKING_300: [WORK, CARRY, CARRY, CARRY, MOVE],
  FIT_WORKING_550: [WORK, WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE],
  FIT_WORKING_800: [WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE],
  FIT_WORKING_1300: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],

  FIT_ATTACK_300: [TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, ATTACK, ATTACK],
  FIT_ATTACK_550: [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK],
  FIT_ATTACK_800: [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK],
  FIT_ATTACK_1300: [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,  ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK],

  FIT_RANGED_300: [MOVE, MOVE, MOVE, RANGED_ATTACK],
  FIT_RANGED_550: [MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK],
  FIT_RANGED_800: [MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK],
  FIT_RANGED_1300: [MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK ],
});
